services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 🧠 Kafka readiness gate (CLAVE)
  kafka-init:
    image: alpine:3.20
    depends_on:
      - kafka
    command: >
      sh -c "
      echo 'Waiting for Kafka...';
      apk add --no-cache netcat-openbsd;
      until nc -z kafka 9092; do
        echo 'Kafka not ready yet...';
        sleep 2;
      done;
      echo 'Kafka is ready';
      "

  bidder:
    build: ./bidder
    ports:
      - "8000:8000"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      redis:
        condition: service_started

  campaign_manager:
    build: ./campaign_manager
    ports:
      - "7000:7000"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
      redis:
        condition: service_started